# Dockerfile.ingestion
FROM python:3.10-slim

USER root

RUN apt-get update && apt-get install -y gcc python3-dev && apt-get clean
RUN pip install confluent-kafka

WORKDIR /app
COPY ./scripts/kafka_consumer/* .

CMD ["python", "-u", "main.py"]