FROM python:3.10-slim

RUN apt-get update && apt-get install -y default-jre-headless && apt-get clean

WORKDIR /app

COPY ./scripts/visual/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]